---
- name: Add Helm REPO
  shell: helm repo add {{ repo_name }} {{ url_repo_helm }}
  register: prometheus_add_repo

- name: Helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: Installling Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install
