name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install ansible
          pip install ansible-lint
      - name: Run Ansible Lint
        run: ansible-lint
      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: './'
          args: >
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.md, **/*.txt, **/*.ini, **/*.conf
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey="isnowheart_lab-ansible_AYdemqJJ_aE1HNgLETEK" 
            -Dsonar.projectName="lab-ansible" 
            -Dsonar.ansible.playbook=main.yml
            -Dsonar.ansible.rolesdir=roles
